from __future__ import annotations

import enum


class DetectionError(enum.Enum):
    NO_FACE = 'ERR_NO_FACE'
    MULTIPLE_FACES = 'ERR_MULTIPLE_FACES'
    NOT_FRONTAL = 'ERR_NOT_FRONTAL'
    GLASSES_DETECTED = 'ERR_GLASSES_DETECTED'
    EYES_CLOSED = 'ERR_EYES_CLOSED'
    MOUTH_NOT_DETECTED = 'ERR_MOUTH_NOT_DETECTED'
    EMOTION_DETECTION_FAILED = 'ERR_EMOTION_DETECTION_FAILED'
    MOUTH_OPEN = 'ERR_MOUTH_OPEN'
